apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  simple-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metric: 
        name: rabbitmq_queue_length
      describedObject:
        apiVersion: v1
        kind: Service
        name: metrics-exporter
      target:
        type: Value
        value: "5"